kind: pipeline
type: docker
name: Docker Build (latest)

steps:
- name: DockerHub
  image: plugins/docker
  settings:
    username: fuzzymistborn
    password:
      from_secret: dockerhub_pw
    repo: fuzzymistborn/wg-easy
    tags: latest
  when:
    event:
    - cron
    cron:
    - weekly

- name: GH Container Registry
  image: plugins/docker
  settings:
    username: fuzzymistborn
    password:
      from_secret: ghcr_pw
    repo: ghcr.io/fuzzymistborn/wg-easy
    registry: ghcr.io
    tags: latest
  when:
    event:
    - cron
    cron:
    - weekly

- name: Send TG Notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: tg_token
    to:
      from_secret: tg_id
    format: markdown
    message: >
      {{#success build.status}}
        ✅  Build for `{{repo.name}}` for `latest-release` was *successful*!
        🌐  [Output]({{build.link}})
      {{else}}
        ❌  Build for `{{repo.name}}` for `lateset-release` has *FAILED*!
        🌐  [Output]({{build.link}})
      {{/success}}
  when:
    status: [ success, failure ]
    
kind: pipeline
type: docker
name: Docker Build (stable cron)
    
- name: DockerHub
  image: plugins/docker
  settings:
    username: fuzzymistborn
    password:
      from_secret: dockerhub_pw
    repo: fuzzymistborn/wg-easy
    tags: stable
  when:
    event:
    - cron
    cron:
    - monthly

- name: GH Container Registry
  image: plugins/docker
  settings:
    username: fuzzymistborn
    password:
      from_secret: ghcr_pw
    repo: ghcr.io/fuzzymistborn/wg-easy
    registry: ghcr.io
    tags: stable
  when:
    event:
    - cron
    cron:
    - monthly

- name: Send TG Notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: tg_token
    to:
      from_secret: tg_id
    format: markdown
    message: >
      {{#success build.status}}
        ✅  Build for `{{repo.name}}` for `stable-cron` was *successful*!
        🌐  [Output]({{build.link}})
      {{else}}
        ❌  Build for `{{repo.name}}` for `stable-cron` has *FAILED*!
        🌐  [Output]({{build.link}})
      {{/success}}
  when:
    status: [ success, failure ]
    
kind: pipeline
type: docker
name: Docker Build (stable release)
    
- name: DockerHub
  image: plugins/docker
  settings:
    username: fuzzymistborn
    password:
      from_secret: dockerhub_pw
    repo: fuzzymistborn/wg-easy
    tags: stable
  when:
    ref:
    - refs/tags/*

- name: GH Container Registry
  image: plugins/docker
  settings:
    username: fuzzymistborn
    password:
      from_secret: ghcr_pw
    repo: ghcr.io/fuzzymistborn/wg-easy
    registry: ghcr.io
    tags: stable
  when:
    ref:
    - refs/tags/*

- name: Send TG Notification
  image: appleboy/drone-telegram
  settings:
    token:
      from_secret: tg_token
    to:
      from_secret: tg_id
    format: markdown
    message: >
      {{#success build.status}}
        ✅  Build for `{{repo.name}}` for `stable-release` was *successful*!
        🌐  [Output]({{build.link}})
      {{else}}
        ❌  Build for `{{repo.name}}` for `stable-release` has *FAILED*!
        🌐  [Output]({{build.link}})
      {{/success}}
  when:
    status: [ success, failure ]
